Clear cache
ref. https://app.circleci.com/pipelines/github/sue445/cure-mastodon-bots/4483/workflows/fb6cc680-b83b-45d6-9180-a87261997fb1/jobs/5208

```
LoadError: libffi.so.7: cannot open shared object file: No such file or directory - /home/circleci/app/vendor/bundle/ruby/3.1.0/gems/ffi-1.15.5/lib/ffi_c.so
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/ffi-1.15.5/lib/ffi.rb:5:in `require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/ffi-1.15.5/lib/ffi.rb:5:in `rescue in <top (required)>'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/ffi-1.15.5/lib/ffi.rb:2:in `<top (required)>'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/llhttp-ffi-0.4.0/lib/llhttp.rb:3:in `require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/llhttp-ffi-0.4.0/lib/llhttp.rb:3:in `<top (required)>'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/http-5.1.0/lib/http/response/parser.rb:3:in `require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/http-5.1.0/lib/http/response/parser.rb:3:in `<top (required)>'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/http-5.1.0/lib/http.rb:16:in `require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/http-5.1.0/lib/http.rb:16:in `<top (required)>'
/home/circleci/app/vendor/bundle/ruby/3.1.0/bundler/gems/mastodon-api-69adfb4f6c4f/lib/mastodon/rest/request.rb:2:in `require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/bundler/gems/mastodon-api-69adfb4f6c4f/lib/mastodon/rest/request.rb:2:in `<top (required)>'
/home/circleci/app/vendor/bundle/ruby/3.1.0/bundler/gems/mastodon-api-69adfb4f6c4f/lib/mastodon/rest/utils.rb:1:in `require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/bundler/gems/mastodon-api-69adfb4f6c4f/lib/mastodon/rest/utils.rb:1:in `<top (required)>'
/home/circleci/app/vendor/bundle/ruby/3.1.0/bundler/gems/mastodon-api-69adfb4f6c4f/lib/mastodon/rest/statuses.rb:1:in `require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/bundler/gems/mastodon-api-69adfb4f6c4f/lib/mastodon/rest/statuses.rb:1:in `<top (required)>'
/home/circleci/app/vendor/bundle/ruby/3.1.0/bundler/gems/mastodon-api-69adfb4f6c4f/lib/mastodon/rest/api.rb:1:in `require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/bundler/gems/mastodon-api-69adfb4f6c4f/lib/mastodon/rest/api.rb:1:in `<top (required)>'
/home/circleci/app/vendor/bundle/ruby/3.1.0/bundler/gems/mastodon-api-69adfb4f6c4f/lib/mastodon/rest/client.rb:2:in `require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/bundler/gems/mastodon-api-69adfb4f6c4f/lib/mastodon/rest/client.rb:2:in `<top (required)>'
/home/circleci/app/vendor/bundle/ruby/3.1.0/bundler/gems/mastodon-api-69adfb4f6c4f/lib/mastodon.rb:5:in `require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/bundler/gems/mastodon-api-69adfb4f6c4f/lib/mastodon.rb:5:in `<top (required)>'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/runtime.rb:60:in `require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/runtime.rb:55:in `each'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/runtime.rb:55:in `block in require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/runtime.rb:44:in `each'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/runtime.rb:44:in `require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler.rb:175:in `require'
/home/circleci/app/Rakefile:17:in `block in <top (required)>'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:58:in `load'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:58:in `kernel_load'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:23:in `run'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/cli.rb:479:in `exec'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/cli.rb:31:in `dispatch'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/cli.rb:25:in `start'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/exe/bundle:49:in `block in <top (required)>'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/exe/bundle:37:in `<top (required)>'
/usr/local/bin/bundle:25:in `load'
/usr/local/bin/bundle:25:in `<main>'

Caused by:
LoadError: cannot load such file -- 3.1/ffi_c
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/ffi-1.15.5/lib/ffi.rb:3:in `require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/ffi-1.15.5/lib/ffi.rb:3:in `<top (required)>'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/llhttp-ffi-0.4.0/lib/llhttp.rb:3:in `require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/llhttp-ffi-0.4.0/lib/llhttp.rb:3:in `<top (required)>'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/http-5.1.0/lib/http/response/parser.rb:3:in `require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/http-5.1.0/lib/http/response/parser.rb:3:in `<top (required)>'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/http-5.1.0/lib/http.rb:16:in `require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/http-5.1.0/lib/http.rb:16:in `<top (required)>'
/home/circleci/app/vendor/bundle/ruby/3.1.0/bundler/gems/mastodon-api-69adfb4f6c4f/lib/mastodon/rest/request.rb:2:in `require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/bundler/gems/mastodon-api-69adfb4f6c4f/lib/mastodon/rest/request.rb:2:in `<top (required)>'
/home/circleci/app/vendor/bundle/ruby/3.1.0/bundler/gems/mastodon-api-69adfb4f6c4f/lib/mastodon/rest/utils.rb:1:in `require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/bundler/gems/mastodon-api-69adfb4f6c4f/lib/mastodon/rest/utils.rb:1:in `<top (required)>'
/home/circleci/app/vendor/bundle/ruby/3.1.0/bundler/gems/mastodon-api-69adfb4f6c4f/lib/mastodon/rest/statuses.rb:1:in `require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/bundler/gems/mastodon-api-69adfb4f6c4f/lib/mastodon/rest/statuses.rb:1:in `<top (required)>'
/home/circleci/app/vendor/bundle/ruby/3.1.0/bundler/gems/mastodon-api-69adfb4f6c4f/lib/mastodon/rest/api.rb:1:in `require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/bundler/gems/mastodon-api-69adfb4f6c4f/lib/mastodon/rest/api.rb:1:in `<top (required)>'
/home/circleci/app/vendor/bundle/ruby/3.1.0/bundler/gems/mastodon-api-69adfb4f6c4f/lib/mastodon/rest/client.rb:2:in `require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/bundler/gems/mastodon-api-69adfb4f6c4f/lib/mastodon/rest/client.rb:2:in `<top (required)>'
/home/circleci/app/vendor/bundle/ruby/3.1.0/bundler/gems/mastodon-api-69adfb4f6c4f/lib/mastodon.rb:5:in `require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/bundler/gems/mastodon-api-69adfb4f6c4f/lib/mastodon.rb:5:in `<top (required)>'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/runtime.rb:60:in `require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/runtime.rb:55:in `each'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/runtime.rb:55:in `block in require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/runtime.rb:44:in `each'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/runtime.rb:44:in `require'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler.rb:175:in `require'
/home/circleci/app/Rakefile:17:in `block in <top (required)>'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:58:in `load'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:58:in `kernel_load'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:23:in `run'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/cli.rb:479:in `exec'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/cli.rb:31:in `dispatch'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/cli.rb:25:in `start'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/exe/bundle:49:in `block in <top (required)>'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/home/circleci/app/vendor/bundle/ruby/3.1.0/gems/bundler-2.2.33/exe/bundle:37:in `<top (required)>'
/usr/local/bin/bundle:25:in `load'
/usr/local/bin/bundle:25:in `<main>'
Tasks: TOP => bot:on_air => environment
(See full trace by running task with --trace)
```