Use syobocal gem instead of forked repo
Wercker bundle installed cache is often broken :cry:

```
bundle install --path /pipeline/cache/bundle-install/ --jobs=4 --retry 3
The git source `git://github.com/sue445/syobocal.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
error: index file objects/pack/pack-2b483bcf5566cd2daca455215899df753a0ba676.idx is too small
error: index file objects/pack/pack-2b483bcf5566cd2daca455215899df753a0ba676.idx is too small
Fetching git://github.com/sue445/syobocal.git

error: index file objects/pack/pack-2b483bcf5566cd2daca455215899df753a0ba676.idx is too small
error: index file objects/pack/pack-2b483bcf5566cd2daca455215899df753a0ba676.idx is too small
error: refs/heads/master does not point to a valid object!
error: index file objects/pack/pack-2b483bcf5566cd2daca455215899df753a0ba676.idx is too small
error: index file objects/pack/pack-2b483bcf5566cd2daca455215899df753a0ba676.idx is too small
error: refs/heads/time_with_zone does not point to a valid object!
error: index file objects/pack/pack-2b483bcf5566cd2daca455215899df753a0ba676.idx is too small
error: index file objects/pack/pack-2b483bcf5566cd2daca455215899df753a0ba676.idx is too small
```